### ISSUE TITLE
Train with other datasets

### ISSUE THREAD

**Issue by cxmscb** [Gabriel-SGama/Semantic-SuperPoint#3]
I would like to train the models with other datasets, but have some confusions.
1. What is the relationship between the code `Train_model_frontend_all.py` and `Train_model_heatmap_all.py` ? 
2. Does `*_all_ct.py` in the readme means `*_all_and.py`?
3. ModuleNotFoundError: No module named 'utils.loss_functions.min_norm_solvers'

**Comment by Gabriel-SGama** [comment]
1. The class in the `Train_model_heatmap_all.py` inherits from `Train_model_frontend_all.py`. I don't think that is needed (just defining everything on the same class probably is goint to work as well), but the original code did this way, so I didn't change.
2.  Yes, `*_all_ct.py` means `*_all_ang.py`. The "ang" is an abbreviation of the central dir. + task tensioner's author, but later, I decided to change it to ct but didn't change the files. I will change it back to `_ang` to keep everything the same.
3. `ModuleNotFoundError: No module named 'utils.loss_functions.min_norm_solvers'` This error happens because the code used to implement the central direction + tensor method is not publicly available, so I removed from this repository, therefore the *_ang files will not work now.

**Comment by cxmscb** [comment]
Thanks for the help. In addition, I find the released models are not robust against the vertical flip or 
 the horizontal flip. Could you provider  some clues about how to apply this transformation in the training?

**Comment by Gabriel-SGama** [comment]
To add this transformation, you would need to change the loader file of the desired dataset in the datasets folder. Changing the config file to activate or deactivate this transformation would be beneficial.

**Comment by cxmscb** [comment]
Thanks for your help.
