### ISSUE TITLE
About the unc+ct loss

### ISSUE THREAD

**Issue by cxmscb** [Gabriel-SGama/Semantic-SuperPoint#5]
Thanks for the great work!!! I am interested about the implementation of the unc+ct loss for the multi-task learning, and is there any plan to release the code for the unc loss?

**Comment by Gabriel-SGama** [comment]
I didn't implement an unc+ct version of the loss because I would be applying two multi-task losses at the same time (I don't think this would work). If you are asking for the SSp+unc, the loss implementation is at the beginning of the file `Train_model_heatmap_all.py`. If you are asking for the ct method, I don't plan on sharing it because the authors didn't publicly share the code.
